name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
          - runner: self-hosted
            arch: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/Gomasy/mastodon
          flavor: |
            latest=auto
          tags: |
            type=raw,value=latest-${{ matrix.arch }},enable={{is_default_branch}}
            type=raw,value={{branch}}-${{ matrix.arch }},enable=${{ github.ref != format('refs/heads/{0}', 'master') }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
